CloudPRNT_Solution/Controllers/DeviceTableController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CloudPRNT_Solution.Models;
using Microsoft.EntityFrameworkCore;
using CloudPRNT_Solution.Data;



namespace CloudPRNT_Solution.Controllers;

public class DeviceTableController : Controller
{
    private readonly DeviceTableContext _context;

    public DeviceTableController(DeviceTableContext context){
         _context = context;
    }
    public IActionResult Create(){

        return View();
    }
    

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddPrinter([Bind("Id, PrinterMac, QueueID, PrintWidth, Status, ClientType, ClientVerion, LastPoll")] DeviceTable deviceInfo ){

        if (ModelState.IsValid){
            
            var printerMacLower = deviceInfo.PrinterMac.ToLower();
            deviceInfo.PrinterMac = printerMacLower;
            deviceInfo.QueueID = deviceInfo.QueueID;
            _context.Add(deviceInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Management");

        }
        return View(deviceInfo);
    }

    // GET: PrintQueue/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.DeviceTable == null)
        {
            return NotFound();
        }

        var deviceTable = await _context.DeviceTable
            .FirstOrDefaultAsync(m => m.Id == id);
        if (deviceTable == null)
        {
            return NotFound();
        }

        return View(deviceTable);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteDevice(int id)
    {
        if (_context.DeviceTable == null)
        {
            return Problem("Entity set 'DeviceTableContext.DeviceTable'  is null.");
        }
        var deviceTable = await _context.DeviceTable.FindAsync(id);
        if (deviceTable != null)
        {
            _context.DeviceTable.Remove(deviceTable);
        }
        
        await _context.SaveChangesAsync();
        return RedirectToAction("Index", "Management");
    }

    private bool DeviceTableExists(int id)
    {
        return _context.DeviceTable.Any(e => e.Id == id);
    }
}

CloudPRNT_Solution/Views/DeviceTable/Create.cshtml
@model CloudPRNT_Solution.Models.DeviceTable

@{
    ViewData["Title"] = "Create";
}

<h3>Add a new Printer</h3>
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddPrinter" asp-controller="DeviceTable" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    
            <div class="form-group">
                 <label asp-for="PrinterMac" class="control-label"></label>
                <input asp-for="PrinterMac" class="form-control" />
                <span asp-validation-for="PrinterMac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QueueID" class="control-label"></label>
                <input asp-for="QueueID" class="form-control" />
                <span asp-validation-for="QueueID" class="text-danger"></span>
            </div>
            <h1></h1>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Add Printer</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Management" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CloudPRNT_Solution/Views/DeviceTable/Delete.cshtml
@model CloudPRNT_Solution.Models.DeviceTable

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this printer?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrinterMac)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrinterMac)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QueueID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QueueID)
        </dd>
    </dl>
    
    <form  asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Management" asp-action="Index">Back to List</a>
    </form>
</div>