CloudPRNT_Solution/Controllers/LocationTableController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CloudPRNT_Solution.Models;
using Microsoft.EntityFrameworkCore;
using CloudPRNT_Solution.Data;



namespace CloudPRNT_Solution.Controllers;

public class LocationTableController : Controller
{
    private readonly LocationTableContext _context;

    public LocationTableController(LocationTableContext context){
         _context = context;
    }
    public IActionResult Create(){

        return View();
    }
    

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddLocation([Bind("Id, LocationName")] LocationTable locationInfo ){

        if (ModelState.IsValid){
            
            locationInfo.LocationName = locationInfo.LocationName;
            _context.Add(locationInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Management");

        }
        return View(locationInfo);
    }


    // GET: PrintQueue/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.LocationTable == null)
        {
            return NotFound();
        }

        var locationTable = await _context.LocationTable
            .FirstOrDefaultAsync(m => m.Id == id);
        if (locationTable == null)
        {
            return NotFound();
        }

        return View(locationTable);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteLocation(int id)
    {
        if (_context.LocationTable == null)
        {
            return Problem("Entity set 'LocationTableContext.LocationTable'  is null.");
        }
        var locationTable = await _context.LocationTable.FindAsync(id);
        if (locationTable != null)
        {
            _context.LocationTable.Remove(locationTable);
        }
        
        await _context.SaveChangesAsync();
        return RedirectToAction("Index", "Management");
    }

    private bool LocationTableExists(int id)
    {
        return _context.LocationTable.Any(e => e.Id == id);
    }

}

CloudPRNT_Solution/Views/LocationTable/Create.cshtml
@model CloudPRNT_Solution.Models.LocationTable

@{
    ViewData["Title"] = "Create";
}

<h3>Add a new Location</h3>
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddLocation" asp-controller="LocationTable" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="LocationName" class="control-label"></label>
                <input asp-for="LocationName" class="form-control" />
                <span asp-validation-for="LocationName" class="text-danger"></span>
            </div>
            <h1></h1>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Add Location</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Management" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CloudPRNT_Solution/Views/LocationTable/Delete.cshtml
@model CloudPRNT_Solution.Models.LocationTable

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this location?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocationName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocationName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Management" asp-action="Index">Back to List</a>
    </form>
</div>